### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by caderek** [kiwphi/pop-shoot#13]
I assume that you meant for the project to be open-source, but without specifying a license, it defaults to being proprietary. From  [Github Docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license):

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The [Open Source Guide](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) provides additional guidance on choosing the correct license for your project.

**Comment by TechnologyClassroom** [comment]
I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by kiwphi** [comment]
Definitely adding a license, I was thinking of the MIT or GLP3, but I'm not sure how to tackle this while having assets that are not mine in the repo. Everything is the assets/ directory should not fall under the license since it's not mine. Any suggestion on how to apply the license to the code only, without complicating things?

**Comment by caderek** [comment]
@kiwphi You can see how I did it for my project: https://github.com/sharechess/sharechess.github.io

Basically I have a normal license for the code, and [credits file](https://github.com/sharechess/sharechess.github.io/blob/main/CREDITS.md) for assets, with a note in README.

**Comment by kiwphi** [comment]
#16 
Thank you @caderek & @TechnologyClassroom
